# Generated by Django 5.1.15 on 2026-04-23 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('activity_done', models.TextField(blank=True, null=True)),
                ('student_response', models.TextField(blank=True, null=True)),
                ('behavior_notes', models.TextField(blank=True, null=True)),
                ('improvement_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('general_notes', models.TextField(blank=True, null=True)),
                ('skip_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='timetable.period')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Report',
                'verbose_name_plural': 'Session Reports',
                'db_table': 'session_reports',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='session_media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='student_sessions.sessionreport')),
            ],
            options={
                'verbose_name': 'Session Media',
                'verbose_name_plural': 'Session Media',
                'db_table': 'session_media',
            },
        ),
        migrations.CreateModel(
            name='SessionReportStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_notes', models.TextField(blank=True, null=True)),
                ('improvement_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('was_present', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='student_sessions.sessionreport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='students.student')),
            ],
            options={
                'verbose_name': 'Session Report Student',
                'verbose_name_plural': 'Session Report Students',
                'db_table': 'session_report_students',
            },
        ),
        migrations.AddIndex(
            model_name='sessionreport',
            index=models.Index(fields=['period', 'date'], name='session_rep_period__923182_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionreport',
            index=models.Index(fields=['teacher', 'date'], name='session_rep_teacher_756bde_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionreport',
            index=models.Index(fields=['status'], name='session_rep_status_5a621c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionreport',
            unique_together={('period', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionreportstudent',
            unique_together={('session_report', 'student')},
        ),
    ]
