# Generated by Django 5.1.15 on 2026-04-23 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('autism_level', models.CharField(choices=[('Level1', 'Level 1 - Requiring Support'), ('Level2', 'Level 2 - Requiring Substantial Support'), ('Level3', 'Level 3 - Requiring Very Substantial Support')], default='Level1', max_length=10)),
                ('enrollment_date', models.DateField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('is_active', models.BooleanField(default=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('student_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='students_name_ead02e_idx'), models.Index(fields=['is_active'], name='students_is_acti_4aecc9_idx'), models.Index(fields=['autism_level'], name='students_autism__34b990_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('medical', 'Medical Report'), ('assessment', 'Assessment Report'), ('consent', 'Consent Form'), ('birth_cert', 'Birth Certificate'), ('photo_id', 'Photo ID'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'db_table': 'student_documents',
            },
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('sibling', 'Sibling'), ('other', 'Other')], default='father', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Parent',
                'verbose_name_plural': 'Student Parents',
                'db_table': 'student_parents',
                'indexes': [models.Index(fields=['student', 'parent'], name='student_par_student_f5ab2a_idx')],
                'unique_together': {('student', 'parent')},
            },
        ),
    ]
